version: "3.8"
services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - /home/syhan/influxdb/influxdb.conf:/etc/influxdb.conf:ro 
      - /home/syhan/influxdb/:/var/lib/influxdb
    ports:
      - "8086:8086"
    restart: always
    networks:
        - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
        - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "5050:5050"
    depends_on: 
      - influxdb
      - mosquitto
    restart: always
    volumes:
        - /home/syhan/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
        - monitoring

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    networks:
        - monitoring
    volumes:
      - /home/syhan/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - /home/syhan/mosquitto/data/:/mosquitto/data
      - /home/syhan/mosquitto/log/:/mosquitto/log

networks:
    monitoring:

volumes:
    grafana-volume:
